TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += hegauge.db
DATA += hegauge.proto

#=======================================
include $(TOP)/configure/RULES
